source_sqlserver:
  server: macotech-database-1.c9ccouqwg4es.us-east-2.rds.amazonaws.com
  port: 1433
  database: nombre_de_tu_bd
  username: Estancia2
  password: "0n55KV/zuxh\\"
  driver: ODBC Driver 17 for SQL Server

target_postgres:
  host: data-warehouse-database.c9ccouqwg4es.us-east-2.rds.amazonaws.com
  port: 5432
  database: macotechwarehouse
  user: postgres
  password: ",58!0a`Br<^q"
  table: freightsummary
